browser:
  path: C:\Users\example\AppData\Local\Vivaldi\Application\vivaldi.exe
  default: Default # The folder name of the default profile

selectprofile: # All URLs listed here will show a dialogue box that prompts the user to choose a profile
  - https://decision1.example.com
  - https://decision2.example.com

mapping:
  - name: "Work" # Name it however you like
    folder: "Profile 1" # Must be the correct profile folder
    urls: # URLs will be normalized, only the host (domain) will be checked
      - https://company.example.com/
      - https://something.else.example.com
